defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: gnn
- task: forecaster
- training: peft
- _self_


# set to true to switch on config validation
config_validation: True

training:
  peft_config:
    _target_: ???
    config: ???
